version: '3'
services:
  nginx:
    image: nginx:latest
    depends_on:
      certbot:
        condition: service_completed_successfully
      certbot2:
        condition: service_completed_successfully
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "4443:4443"
    environment:
      - DOMAIN
      - LAN_IP
      - DOMAIN2
      - LAN_IP2
    volumes:
      - ./nginx:/docker-entrypoint.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf.template
      - ./certs:/etc/nginx/certs

  certbot:
    build:
      context: ./certbot
      dockerfile: Dockerfile
      args:
        DOMAIN:
        EMAIL:
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certbot/cloudflare.ini:/etc/letsencrypt/cloudflare.ini
      - ./certbot/logs:/var/log/letsencrypt
    command: certonly --dns-cloudflare --dns-cloudflare-credentials /etc/letsencrypt/cloudflare.ini -d ${DOMAIN} --non-interactive --agree-tos --email ${EMAIL} 
  certbot2:
    depends_on:
      certbot:
        condition: service_completed_successfully
    build:
      context: ./certbot
      dockerfile: Dockerfile
      args:
        DOMAIN2:
        EMAIL:
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certbot/cloudflare.ini:/etc/letsencrypt/cloudflare.ini
      - ./certbot/logs:/var/log/letsencrypt
    command: certonly --dns-cloudflare --dns-cloudflare-credentials /etc/letsencrypt/cloudflare.ini -d ${DOMAIN2} --non-interactive --agree-tos --email ${EMAIL}
