version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=${DOMAIN}
      - LAN_IP=${LAN_IP}
    volumes:
      - ./nginx:/docker-entrypoint.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf.template
      - ./certs:/etc/nginx/certs

  certbot:
    build:
      context: ./certbot
      dockerfile: Dockerfile
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certbot/cloudflare.ini:/etc/letsencrypt/cloudflare.ini
      - ./certbot/logs:/var/log/letsencrypt
    environment:
      - DOMAIN
      - LAN_IP
    command: certonly --dns-cloudflare --dns-cloudflare-credentials /etc/letsencrypt/cloudflare.ini -d ${DOMAIN} --non-interactive --agree-tos
